apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    # RabbitMQ Config
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    loopback_users.guest = false
    cluster_partition_handling = autoheal

  enabled_plugins: |
    # RabbitMQ plugins
    [rabbitmq_management],[rabbitmq_peer_discovery_k8s]

  definitions.json: |
    {
      "rabbit_version": "3.9.8",
      "users": [
        {
          "name": "admin",
          "password_hash": "ZV2Z9lg1c9xr6KyhElEvv7nm4qSmq1YxiAOgiSV0JiXEx8XY",
          "tags": "administrator"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "admin",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ]
    }
